#!/bin/sh

PACKAGE=conquest-dicom-server

VERSION=`dpkg-parsechangelog | sed -n -e 's/^Version: \(.*\)-[^-]*$/\1/p'`

#ftp://ftp-rt.nki.nl/outbox/MarcelVanHerk/dicomserver/dicomserver1417c.zip
#ftp://ftp-rt.nki.nl/outbox/MarcelVanHerk/dicomserver/conquestlinux1417c.tar.gz
TARFILE=${PACKAGE}_${VERSION}.orig.tar.gz
UPSTREAM=conquestlinux1417c.tar.gz

FOLDER=${PACKAGE}-${VERSION}

wget -c -O /tmp/$UPSTREAM ftp://ftp-rt.nki.nl/outbox/MarcelVanHerk/dicomserver/${UPSTREAM}

mkdir ${FOLDER}
tar xvf /tmp/${UPSTREAM} -C ${FOLDER}

# cleanup
# conv copy of libjasper (sigh)
#rm -rf ${FOLDER}/jasper-1.900.1-6ct/
# conv copy of libjpeg 6c:
#rm -rf ${FOLDER}/jpeg-6c/
# conv copy of lua 5.1.4
rm -rf ${FOLDER}/lua_*
# conv copy of sqlite3
rm ${FOLDER}/sqlite3.*
# ZeroBraneStudio
rm -rf ${FOLDER}/ZeroBraneStudio*
# clibs windows
rm -rf ${FOLDER}/clibs*
# logs
rm -f ${FOLDER}/*.log
# mak* files
rm -f ${FOLDER}/mak*

# remove DICOM test files:
rm -rf ${FOLDER}/data/samples/

# scary stuff:
rm ${FOLDER}/ActiveFormProj1.ocx

# Unused PDFs
rm ${FOLDER}/windowsmanual.pdf
rm ${FOLDER}/jasper-1.900.1-6ct/doc/*.pdf

# zip file:
rm ${FOLDER}/jpeg-6c/jpeg-6c-changesmvh2.zip

# vc80.pdb ?
find ${FOLDER} -name vc80.pdb -delete

# remove executable bit from lua examples
chmod a-x ${FOLDER}/lua/*

# 
rm ${FOLDER}/data/dbase/conquest.db3

# make distclean
(cd ${FOLDER}/jasper-1.900.1-6ct && make distclean)
(cd ${FOLDER}/jpeg-6c && make distclean)

GZIP="--best --no-name" tar cvfz ${TARFILE} ${FOLDER} 
rm -rf ${FOLDER}
