#!/bin/sh

PACKAGE=conquest-dicom-server
VERSION=`dpkg-parsechangelog | sed -n -e 's/^Version: \(.*\)-[^-]*$/\1/p'`

help2man -h "-?" -N -s 1 -n "UCDMC/NKI DICOM server thread and PACS utility application" \
         --no-discard-stderr --version-string $VERSION -m "ConQuest DICOM server" -S \
         "The Netherlands Cancer Institute; RT Department" -o dgate.1 ./dgate
